version: '3'
services:
  app:
    hostname: facial-reload
    container_name: facial-reload
    build:
      context: ./
      dockerfile: Dockerfile
    image: facial-reload
    volumes:
      - ./:/app
      - ./weights:/root/.deepface/weights/
    ports:
      - '5000:5000'
    networks:
      - api-network
    env_file:
      - ./.env
  chroma:
    hostname: chroma
    container_name: chroma
    image: chromadb/chroma
    volumes:
      - index_data:/chroma/chroma
    ports:
      - '5001:8000'
    env_file:
      - ./.env.chroma
    networks:
      - api-network


volumes:
  index_data:
    driver: local
  

networks:
  api-network:
    driver: bridge