version: '3'
services:
  app:
    hostname: facial-reload
    container_name: facial-reload
    build:
      context: ./
      dockerfile: Dockerfile
    image: facial-reload
    volumes:
      - ./:/app
      - ./weights:/root/.deepface/weights/
      - ./db:/app/db
    ports:
      - '5000:5000'
    networks:
      - api-network
    env_file:
      - ./.env

networks:
  api-network:
    driver: bridge